"""Prompt length caps — the wired prompt nobody can shorten.

Port of nanoodle-js src/prompt-caps.mjs. Keep the two in step.

Many image and video models reject an over-long prompt at NanoGPT's route, before the
provider is called and before anything is charged::

    400 {"error":"Your prompt is too long for Qwen Image 3. Please shorten it to 800
         characters or less (current: 831 characters).","code":"prompt_too_long"}

Free, but a dead end. In a graph the prompt is generated, not typed — an LLM node writes
it and a wire carries it into the image node — so "please shorten it" names something no
caller controls directly. For a headless or agent-driven run that is the whole workflow
lost to a limit nobody was told about.

So: trim it to fit at a sentence boundary (``fit_prompt_text``) and REPORT it — a
``prompt-trimmed`` progress event plus a Python warning. A silent trim would be a bug; the
report is what makes the trim defensible. A cap we did not know is learned from the live
400 (``prompt_cap_from_error``) and kept on the Workflow, so a retry states the limit
instead of rediscovering it.

What this deliberately does NOT do is edit the graph's own prompts to avoid the trim. An
llm node's system prompt goes to the model exactly as its author wrote it. To inject a
"keep it under N characters" directive on their behalf would silently change what their
workflow produces.

The image/video catalogs advertise no prompt limit at all (checked live 2026-07-26), hence
the probed table below. Audio caps ARE catalog metadata (supported_parameters.max_chars)
and are read from the opt-in catalog instead — never listed here. An absent id means no cap
found, or never probed: unknown stays unconstrained, which matches this library's
permissive-gate rule everywhere else.

Table generated by nanoodle's scripts/probe-prompt-caps.mjs. Keep it in step with the
copies in nanoodle-js, and in nanoodle's index.html / play.html.
"""

import re

# Character caps by model id. Mirrors nanoodle-js PROMPT_CAPS verbatim.
PROMPT_CAPS = {
    "generated": "2026-07-26",
    "image": {
        "step-image-edit-2": 512,
        "qwen-image-3": 800,
        "z-image-turbo": 1200,
        "z-image-turbo-image-to-image": 1200,
        "z-image-turbo-lora": 1200,
        "2dn-pony-v2": 3000,
        "aniflatmix-anime": 3000,
        "aniflatmix-anime-sfwnsfw": 3000,
        "animagine-xl-31": 3000,
        "artiwaifu-diffusion": 3000,
        "atomix-xl": 3000,
        "boltning": 3000,
        "crystal-clear-xl": 3000,
        "crystal-clear-xlightning": 3000,
        "cyberrealistic-pony-v9": 3000,
        "cyberrealistic-xl": 3000,
        "dreamshaper-v1": 3000,
        "dreamshaper-xl": 3000,
        "fluently-xl": 3000,
        "flux-schnell": 3000,
        "hassaku-hentai": 3000,
        "hidream": 3000,
        "hidream-i1-fast": 3000,
        "ideogram:4@0": 3000,
        "infinite-illustrious": 3000,
        "juggernaut-lightning-flux": 3000,
        "juggernaut-pro-flux": 3000,
        "juggernaut-z": 3000,
        "miusmius-xl": 3000,
        "nsfw-gen-illustrious": 3000,
        "persona:376130@2456367": 3000,
        "pixelwave": 3000,
        "proteus": 3000,
        "prunaai:1@1": 3000,
        "qwen-image": 3000,
        "realpony-xl": 3000,
        "rev-animated": 3000,
        "riverflow-2-fast": 3000,
        "riverflow-2-max": 3000,
        "riverflow-2-standard": 3000,
        "runware:106@1": 3000,
        "runware:107@1": 3000,
        "stable-diffusion-xl-turbo": 3000,
        "stoiqo-new-reality": 3000,
        "wai-illustrious-sdxl": 3000,
    },
    "video": {
        "minimax-hailuo-02": 2000,
        "lightricks-ltx-2-fast": 3000,
    },
}

# node type -> which catalog its model comes from. chat is present so prompt_cap can say
# "no" for it: an LLM's own limit is tokens, and it is never the node being fitted.
CAP_KIND = {
    "llm": "chat", "vision": "chat",
    "image": "image", "edit": "image", "inpaint": "image",
    "tvideo": "video", "ivideo": "video", "vedit": "video", "lipsync": "video",
    "music": "audio", "remix": "audio", "tts": "audio",
}


def _node_type(node):
    if node is None:
        return None
    if isinstance(node, dict):
        return node.get("type")
    return getattr(node, "type", None)


def _node_fields(node):
    if node is None:
        return {}
    if isinstance(node, dict):
        return node.get("fields") or {}
    return getattr(node, "fields", None) or {}


def _catalog_max_chars(catalog, model_id):
    """audio catalog metadata: supported_parameters.max_chars (nanoodle-js catItem)."""
    if not catalog or not model_id:
        return None
    items = catalog.get("audio") if isinstance(catalog, dict) else None
    for item in items or []:
        if isinstance(item, dict) and item.get("id") == model_id:
            params = item.get("supported_parameters") or {}
            cap = params.get("max_chars")
            return cap or None
    return None


def prompt_cap(node, catalog=None, learned=None, fields=None):
    """The prompt character cap for a node, or None when the model has none / we know none.

    ``learned`` (a dict of "kind:id" -> cap) wins over the table: it came from this account
    hitting this model today, and the table is a snapshot. ``fields`` overrides the node's
    own fields, which is how a wired model override is honoured.
    """
    kind = CAP_KIND.get(_node_type(node))
    src = _node_fields(node) if fields is None else (fields or {})
    model_id = src.get("model")
    if not kind or not model_id or kind == "chat":
        return None
    hit = (learned or {}).get("%s:%s" % (kind, model_id))
    if hit:
        return hit
    if kind == "audio":
        return _catalog_max_chars(catalog, model_id)
    return (PROMPT_CAPS.get(kind) or {}).get(model_id) or None


# --- UTF-16 code units -------------------------------------------------------------
# A cap is a count of UTF-16 code units, not of Python code points. NanoGPT's route
# counts what the JavaScript app counts (`String#length`), and nanoodle-js measures the
# same way, so a Python `len()` is the wrong ruler for any prompt outside the Basic
# Multilingual Plane. One emoji is 1 code point and 2 code units; "🎉" * 450 is 450 to
# Python and 900 to the API. Measuring in code points let an over-cap prompt through, and
# cut a trimmed prompt to nearly twice the cap. So measure and cut in code units.
#
# The trick below is that a Python str can hold a lone surrogate, so "the string as UTF-16
# code units" is itself a str: one character per code unit. Every index, slice and rfind
# then behaves exactly as in JavaScript. _from_units puts the pairs back.

_HIGH, _LOW = 0xD800, 0xDC00

# JavaScript String#trim removes WhiteSpace + LineTerminator. That set is NOT Python's
# str.strip() default: Python also strips U+001C..U+001F and U+0085, and does not strip
# U+FEFF. Spell it out so a trimmed prompt is byte-identical in both languages.
_JS_WS = (
    "\t\n\v\f\r "                 # TAB LF VT FF CR SP
    "\u00a0\u1680"                       # NBSP, OGHAM SPACE MARK
    "\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a"
    "\u2028\u2029"                       # LINE / PARAGRAPH SEPARATOR
    "\u202f\u205f\u3000"                 # NARROW NBSP, MEDIUM MATH SPACE, IDEOGRAPHIC SP
    "\ufeff"                             # ZWNBSP - JS trims it, Python str.strip() does not
)


def _js_trim(s):
    """s.trim() as JavaScript defines it."""
    return s.strip(_JS_WS)


def utf16_len(s):
    """Length in UTF-16 code units — what nanoodle-js and the API route count."""
    s = "" if s is None else str(s)
    return len(s.encode("utf-16-le", "surrogatepass")) // 2


def _to_units(s):
    """s with every astral character split into its surrogate pair, one char per unit."""
    if s.isascii():
        return s
    out = []
    for ch in s:
        o = ord(ch)
        if o > 0xFFFF:
            o -= 0x10000
            out.append(chr(_HIGH + (o >> 10)))
            out.append(chr(_LOW + (o & 0x3FF)))
        else:
            out.append(ch)
    return "".join(out)


def _from_units(u):
    """Surrogate pairs back into characters. A LONE surrogate is dropped, never emitted.

    A cut at the cap can land between the two halves of an astral character. JavaScript
    keeps the orphan half; Python must not. A lone surrogate is not encodable as UTF-8, so
    it would break the very request this function exists to make sendable, and json.dumps
    of the trim record would raise. Dropping it costs one code unit, always under the cap.
    """
    if not any(_HIGH <= ord(c) <= 0xDFFF for c in u):
        return u
    out = []
    i, n = 0, len(u)
    while i < n:
        o = ord(u[i])
        if _HIGH <= o <= 0xDBFF and i + 1 < n and _LOW <= ord(u[i + 1]) <= 0xDFFF:
            out.append(chr(0x10000 + ((o - _HIGH) << 10) + (ord(u[i + 1]) - _LOW)))
            i += 2
        elif _HIGH <= o <= 0xDFFF:
            i += 1          # orphan half of a character: drop it
        else:
            out.append(u[i])
            i += 1
    return "".join(out)


def fit_prompt_text(s, cap):
    """Cut to the last sentence end inside the cap, then the last word.

    Never mid-word, and never below 70% of the cap, where honouring a boundary would throw
    away more than the overflow did.
    """
    s = "" if s is None else str(s)
    u = _to_units(s)
    if len(u) <= cap:
        return s
    head = u[:cap]
    floor = int(cap * 0.7)
    sent = max(head.rfind(". "), head.rfind("! "), head.rfind("? "), head.rfind("\n"))
    if sent >= floor:
        return _from_units(_js_trim(head[:sent + 1]))
    word = head.rfind(" ")
    return _from_units(_js_trim(head[:word] if word >= floor else head))


def with_fitted_prompt(node, fields, catalog=None, learned=None):
    """Fit the prompt rather than lose the run to a 400 the caller cannot act on.

    Returns ``(fields, trimmed)``. ``trimmed`` is non-None exactly when the caller owes the
    user an explanation, and reporting it is not optional. ``fields`` is the same object
    when nothing was trimmed, and a copy when it was.
    """
    cap = prompt_cap(node, catalog=catalog, learned=learned, fields=fields)
    p = (fields or {}).get("prompt")
    if not cap or not isinstance(p, str):
        return fields, None
    # lengths are UTF-16 code units throughout — the unit the cap is stated in, and the
    # unit nanoodle-js reports, so the same graph discloses the same figures either side
    was = utf16_len(p)
    if was <= cap:
        return fields, None
    prompt = fit_prompt_text(p, cap)
    out = dict(fields)
    out["prompt"] = prompt
    return out, {"from": was, "to": utf16_len(prompt), "cap": cap}


# NanoGPT phrases the rejection three ways (all live-verified 2026-07-26):
#   {"error":"…Please shorten it to 800 characters or less (current: 831 characters).","code":"prompt_too_long"}
#   {"error":{"message":"…512 characters or less…","code":"prompt_too_long"}}   <- nested
#   {"error":"Prompt is too long. Please keep it under 3000 characters."}       <- no code at all
# so match the sentence, not the envelope. "current: N" is deliberately unmatched — that is
# the length we SENT, and to learn it as the cap would grow the limit with every failure.
_PROMPT_TOO_LONG_RE = re.compile(
    r"(?:shorten (?:it )?to|keep it under|at most|maximum of|limit of)\s*([\d,]{2,})\s*characters",
    re.I)
_TOO_LONG_MARKER_RE = re.compile(r"prompt_too_long|prompt is too long", re.I)


def is_prompt_too_long(msg):
    """True when this API message is a prompt-length rejection."""
    return bool(_TOO_LONG_MARKER_RE.search("" if msg is None else str(msg)))


def prompt_cap_from_error(msg):
    """The cap stated by a live rejection, or None."""
    m = _PROMPT_TOO_LONG_RE.search("" if msg is None else str(msg))
    if not m:
        return None
    value = int(m.group(1).replace(",", ""))
    return value if value > 0 else None


def learn_prompt_cap(learned, node, msg):
    """Bank a cap learned from a live rejection. True when it is new information.

    True is a PROMISE: the caller turns it into "running again should succeed". So only
    bank what ``prompt_cap`` will actually read back. It returns None for kind "chat"
    before it ever consults ``learned``, because an llm or vision node's limit is tokens
    and that node is never the one being fitted. A cap banked under a chat key can
    therefore never be applied, and promising an llm caller a fix would send them into a
    PAID re-run that fails in exactly the same way. Decline instead: the API's own message
    is relayed untouched, which is the honest answer when we cannot prevent the failure.

    This is a deliberate, narrow divergence from nanoodle-js learnPromptCap, which banks
    the chat key and makes the promise. The cut is behaviourally invisible everywhere the
    promise was keepable, and only removes a false one.
    """
    cap = prompt_cap_from_error(msg)
    kind = CAP_KIND.get(_node_type(node))
    model_id = _node_fields(node).get("model")
    if not cap or not kind or not model_id or kind == "chat":
        return False
    key = "%s:%s" % (kind, model_id)
    if learned.get(key) == cap:
        return False
    learned[key] = cap
    return True
