"""Prompt length caps — the wired prompt nobody can shorten.

Port of nanoodle-js src/prompt-caps.mjs. Keep the two in step.

Many image and video models reject an over-long prompt at NanoGPT's route, before the
provider is called and before anything is charged::

    400 {"error":"Your prompt is too long for Qwen Image 3. Please shorten it to 800
         characters or less (current: 831 characters).","code":"prompt_too_long"}

Free, but a dead end. In a graph the prompt is generated, not typed — an LLM node writes
it and a wire carries it into the image node — so "please shorten it" names something no
caller controls directly. For a headless or agent-driven run that is the whole workflow
lost to a limit nobody was told about.

So: trim it to fit at a sentence boundary (``fit_prompt_text``) and REPORT it — a
``prompt-trimmed`` progress event plus a Python warning. A silent trim would be a bug; the
report is what makes the trim defensible. A cap we did not know is learned from the live
400 (``prompt_cap_from_error``) and kept on the Workflow, so a retry states the limit
instead of rediscovering it.

What this deliberately does NOT do is edit the graph's own prompts to avoid the trim. An
llm node's system prompt goes to the model exactly as its author wrote it. To inject a
"keep it under N characters" directive on their behalf would silently change what their
workflow produces.

The image/video catalogs advertise no prompt limit at all (checked live 2026-07-26), hence
the probed table below. Audio caps ARE catalog metadata (supported_parameters.max_chars)
and are read from the opt-in catalog instead — never listed here. An absent id means no cap
found, or never probed: unknown stays unconstrained, which matches this library's
permissive-gate rule everywhere else.

Table generated by nanoodle's scripts/probe-prompt-caps.mjs. Keep it in step with the
copies in nanoodle-js, and in nanoodle's index.html / play.html.
"""

import re

# Character caps by model id. Mirrors nanoodle-js PROMPT_CAPS verbatim.
PROMPT_CAPS = {
    "generated": "2026-07-26",
    "image": {
        "step-image-edit-2": 512,
        "qwen-image-3": 800,
        "z-image-turbo": 1200,
        "z-image-turbo-image-to-image": 1200,
        "z-image-turbo-lora": 1200,
        "2dn-pony-v2": 3000,
        "aniflatmix-anime": 3000,
        "aniflatmix-anime-sfwnsfw": 3000,
        "animagine-xl-31": 3000,
        "artiwaifu-diffusion": 3000,
        "atomix-xl": 3000,
        "boltning": 3000,
        "crystal-clear-xl": 3000,
        "crystal-clear-xlightning": 3000,
        "cyberrealistic-pony-v9": 3000,
        "cyberrealistic-xl": 3000,
        "dreamshaper-v1": 3000,
        "dreamshaper-xl": 3000,
        "fluently-xl": 3000,
        "flux-schnell": 3000,
        "hassaku-hentai": 3000,
        "hidream": 3000,
        "hidream-i1-fast": 3000,
        "ideogram:4@0": 3000,
        "infinite-illustrious": 3000,
        "juggernaut-lightning-flux": 3000,
        "juggernaut-pro-flux": 3000,
        "juggernaut-z": 3000,
        "miusmius-xl": 3000,
        "nsfw-gen-illustrious": 3000,
        "persona:376130@2456367": 3000,
        "pixelwave": 3000,
        "proteus": 3000,
        "prunaai:1@1": 3000,
        "qwen-image": 3000,
        "realpony-xl": 3000,
        "rev-animated": 3000,
        "riverflow-2-fast": 3000,
        "riverflow-2-max": 3000,
        "riverflow-2-standard": 3000,
        "runware:106@1": 3000,
        "runware:107@1": 3000,
        "stable-diffusion-xl-turbo": 3000,
        "stoiqo-new-reality": 3000,
        "wai-illustrious-sdxl": 3000,
    },
    "video": {
        "minimax-hailuo-02": 2000,
        "lightricks-ltx-2-fast": 3000,
    },
}

# node type -> which catalog its model comes from. chat is present so prompt_cap can say
# "no" for it: an LLM's own limit is tokens, and it is never the node being fitted.
CAP_KIND = {
    "llm": "chat", "vision": "chat",
    "image": "image", "edit": "image", "inpaint": "image",
    "tvideo": "video", "ivideo": "video", "vedit": "video", "lipsync": "video",
    "music": "audio", "remix": "audio", "tts": "audio",
}


def _node_type(node):
    if node is None:
        return None
    if isinstance(node, dict):
        return node.get("type")
    return getattr(node, "type", None)


def _node_fields(node):
    if node is None:
        return {}
    if isinstance(node, dict):
        return node.get("fields") or {}
    return getattr(node, "fields", None) or {}


def _catalog_max_chars(catalog, model_id):
    """audio catalog metadata: supported_parameters.max_chars (nanoodle-js catItem)."""
    if not catalog or not model_id:
        return None
    items = catalog.get("audio") if isinstance(catalog, dict) else None
    for item in items or []:
        if isinstance(item, dict) and item.get("id") == model_id:
            params = item.get("supported_parameters") or {}
            cap = params.get("max_chars")
            return cap or None
    return None


def prompt_cap(node, catalog=None, learned=None, fields=None):
    """The prompt character cap for a node, or None when the model has none / we know none.

    ``learned`` (a dict of "kind:id" -> cap) wins over the table: it came from this account
    hitting this model today, and the table is a snapshot. ``fields`` overrides the node's
    own fields, which is how a wired model override is honoured.
    """
    kind = CAP_KIND.get(_node_type(node))
    src = _node_fields(node) if fields is None else (fields or {})
    model_id = src.get("model")
    if not kind or not model_id or kind == "chat":
        return None
    hit = (learned or {}).get("%s:%s" % (kind, model_id))
    if hit:
        return hit
    if kind == "audio":
        return _catalog_max_chars(catalog, model_id)
    return (PROMPT_CAPS.get(kind) or {}).get(model_id) or None


def fit_prompt_text(s, cap):
    """Cut to the last sentence end inside the cap, then the last word.

    Never mid-word, and never below 70% of the cap, where honouring a boundary would throw
    away more than the overflow did.
    """
    s = "" if s is None else str(s)
    if len(s) <= cap:
        return s
    head = s[:cap]
    floor = int(cap * 0.7)
    sent = max(head.rfind(". "), head.rfind("! "), head.rfind("? "), head.rfind("\n"))
    if sent >= floor:
        return head[:sent + 1].strip()
    word = head.rfind(" ")
    return (head[:word] if word >= floor else head).strip()


def with_fitted_prompt(node, fields, catalog=None, learned=None):
    """Fit the prompt rather than lose the run to a 400 the caller cannot act on.

    Returns ``(fields, trimmed)``. ``trimmed`` is non-None exactly when the caller owes the
    user an explanation, and reporting it is not optional. ``fields`` is the same object
    when nothing was trimmed, and a copy when it was.
    """
    cap = prompt_cap(node, catalog=catalog, learned=learned, fields=fields)
    p = (fields or {}).get("prompt")
    if not cap or not isinstance(p, str) or len(p) <= cap:
        return fields, None
    prompt = fit_prompt_text(p, cap)
    out = dict(fields)
    out["prompt"] = prompt
    return out, {"from": len(p), "to": len(prompt), "cap": cap}


# NanoGPT phrases the rejection three ways (all live-verified 2026-07-26):
#   {"error":"…Please shorten it to 800 characters or less (current: 831 characters).","code":"prompt_too_long"}
#   {"error":{"message":"…512 characters or less…","code":"prompt_too_long"}}   <- nested
#   {"error":"Prompt is too long. Please keep it under 3000 characters."}       <- no code at all
# so match the sentence, not the envelope. "current: N" is deliberately unmatched — that is
# the length we SENT, and to learn it as the cap would grow the limit with every failure.
_PROMPT_TOO_LONG_RE = re.compile(
    r"(?:shorten (?:it )?to|keep it under|at most|maximum of|limit of)\s*([\d,]{2,})\s*characters",
    re.I)
_TOO_LONG_MARKER_RE = re.compile(r"prompt_too_long|prompt is too long", re.I)


def is_prompt_too_long(msg):
    """True when this API message is a prompt-length rejection."""
    return bool(_TOO_LONG_MARKER_RE.search("" if msg is None else str(msg)))


def prompt_cap_from_error(msg):
    """The cap stated by a live rejection, or None."""
    m = _PROMPT_TOO_LONG_RE.search("" if msg is None else str(msg))
    if not m:
        return None
    value = int(m.group(1).replace(",", ""))
    return value if value > 0 else None


def learn_prompt_cap(learned, node, msg):
    """Bank a cap learned from a live rejection. True when it is new information."""
    cap = prompt_cap_from_error(msg)
    kind = CAP_KIND.get(_node_type(node))
    model_id = _node_fields(node).get("model")
    if not cap or not kind or not model_id:
        return False
    key = "%s:%s" % (kind, model_id)
    if learned.get(key) == cap:
        return False
    learned[key] = cap
    return True
